from __future__ import annotations

from datetime import datetime
from typing import Literal, Optional

from pydantic import BaseModel, Field


class ExtractedMemory(BaseModel):
    """
    A single atomic memory extracted from a conversation.
    """
    memory_type: Literal[
        "user_preference",
        "user_fact",
        "store_fact",
        "store_pattern",
        "episodic_event",
        "decision",
        "assistant_recommendation",
    ] = Field(description="The semantic classification of the memory.")

    content: str = Field(description="The actual memory text/fact. Should be atomic and self-contained.")
    subject: str = Field(description="The primary entity this memory is about (e.g., 'User', 'Store', 'Rice').")

    source_role: Literal["user", "assistant", "tool", "system"] = Field(
        description="Who originated the fact. Must never be hallucinated as 'user' if generated by the assistant."
    )

    source: Optional[str] = Field(default=None, description="More specific provenance (e.g., 'inventory_tool').")
    evidence: str = Field(description="The exact quote or tool output that proves this memory is valid.")

    confidence: float = Field(ge=0.0, le=1.0, description="Confidence in this memory's truth (0.0 to 1.0).")
    importance: float = Field(ge=0.0, le=1.0, description="How useful this memory will be in the future (0.0 to 1.0).")

    event_time: Optional[datetime] = Field(default=None, description="When the actual event happened, if applicable.")
    valid_from: Optional[datetime] = Field(default=None, description="When this fact became valid.")
    valid_to: Optional[datetime] = Field(default=None, description="When this fact stopped being valid.")
    expires_at: Optional[datetime] = Field(default=None, description="If this is a temporary memory, when to forget it.")

    # Metadata for lifecycle and pinecone tracking
    memory_id: Optional[str] = Field(default=None)
    user_id: Optional[str] = Field(default=None)
    store_id: Optional[str] = Field(default=None)
    
    created_at: Optional[datetime] = Field(default=None)
    last_confirmed_at: Optional[datetime] = Field(default=None)
    
    status: Literal["candidate", "active", "superseded", "archived"] = Field(default="candidate")
    supersedes: Optional[str] = Field(default=None, description="ID of the memory this replaces.")
    
    schema_version: str = Field(default="v2")

class ExtractionResult(BaseModel):
    """
    The structured output from the LLM extraction process.
    """
    memories: list[ExtractedMemory] = Field(
        default_factory=list,
        description="The list of atomic memories extracted from the conversation."
    )
