"""
app/agent/subgraphs/document_generation/generators/excel_generator.py
=======================================================================
Deterministic Excel document generator using openpyxl.
Translates structured ExcelDocumentSpec into a beautifully formatted .xlsx file.
"""

import os
import uuid
from typing import Any
import structlog
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.chart import BarChart, LineChart, PieChart, Reference

LOGGER = structlog.get_logger("vyaparsathi.ai.doc_gen.generators.excel")


def generate_excel_document(spec: dict[str, Any], output_dir: str) -> tuple[str, str]:
    """
    Generate an Excel workbook (.xlsx) deterministically using openpyxl based on spec.

    Args:
        spec: Structured Excel specification dict (matching ExcelDocumentSpec schema)
        output_dir: Directory where temporary .xlsx file will be created

    Returns:
        tuple[file_path, filename]
    """
    os.makedirs(output_dir, exist_ok=True)

    file_id = f"doc_{uuid.uuid4().hex[:12]}"
    raw_filename = spec.get("filename") or spec.get("title") or "report"
    safe_basename = "".join(c if c.isalnum() or c in ("-", "_") else "_" for c in raw_filename.lower())
    safe_basename = safe_basename.strip("_") or "report"
    filename = f"{safe_basename}_{file_id[:8]}.xlsx"
    file_path = os.path.join(output_dir, filename)

    wb = Workbook()
    sheets_spec = spec.get("sheets", [])

    if not sheets_spec:
        sheets_spec = [{
            "name": "Summary",
            "columns": ["Title", "Details"],
            "rows": [[spec.get("title", "Document"), "Generated by Vyapar Sakha"]]
        }]

    default_sheet = wb.active

    # Premium Styling Definitions
    FONT_FAMILY = "Segoe UI"
    
    title_font = Font(name=FONT_FAMILY, size=16, bold=True, color="1F4E79")
    title_fill = PatternFill(start_color="EBF1F5", end_color="EBF1F5", fill_type="solid")

    header_font = Font(name=FONT_FAMILY, size=11, bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")

    row_font = Font(name=FONT_FAMILY, size=10, bold=False, color="1F1F1F")
    row_even_fill = PatternFill(start_color="F8FAFC", end_color="F8FAFC", fill_type="solid")
    row_odd_fill = PatternFill(start_color="FFFFFF", end_color="FFFFFF", fill_type="solid")

    total_font = Font(name=FONT_FAMILY, size=11, bold=True, color="1F4E79")
    total_fill = PatternFill(start_color="EBF1F5", end_color="EBF1F5", fill_type="solid")

    thin_border = Border(
        left=Side(style="thin", color="E0E0E0"),
        right=Side(style="thin", color="E0E0E0"),
        top=Side(style="thin", color="E0E0E0"),
        bottom=Side(style="thin", color="E0E0E0")
    )

    total_border = Border(
        top=Side(style="thin", color="1F4E79"),
        bottom=Side(style="double", color="1F4E79")
    )

    for i, sheet_spec in enumerate(sheets_spec):
        sheet_name = sheet_spec.get("name", f"Sheet{i+1}")[:31]

        if i == 0:
            ws = default_sheet
            ws.title = sheet_name
        else:
            ws = wb.create_sheet(title=sheet_name)

        # Explicitly show gridlines
        ws.views.sheetView[0].showGridLines = True

        columns = sheet_spec.get("columns", [])
        rows = sheet_spec.get("rows", [])
        currency_cols = set(sheet_spec.get("currency_columns", []))
        percentage_cols = set(sheet_spec.get("percentage_columns", []))

        # Row 1: Document Banner / Title
        ws.row_dimensions[1].height = 36
        title_text = spec.get("title", "Report")
        cell_title = ws.cell(row=1, column=1, value=title_text)
        cell_title.font = title_font
        cell_title.alignment = Alignment(horizontal="left", vertical="center", indent=1)

        # Apply banner fill across first few columns
        max_title_col = max(len(columns), 5)
        for c in range(1, max_title_col + 1):
            ws.cell(row=1, column=c).fill = title_fill

        # Start Header at Row 3
        start_row = 3
        ws.row_dimensions[start_row].height = 28

        # Write Header Row
        for col_idx, col_name in enumerate(columns, start=1):
            cell = ws.cell(row=start_row, column=col_idx, value=str(col_name))
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
            cell.border = thin_border

        # Write Data Rows
        current_row = start_row + 1
        for row_idx, row_data in enumerate(rows):
            ws.row_dimensions[current_row].height = 22
            row_fill = row_even_fill if row_idx % 2 == 1 else row_odd_fill

            for col_idx, value in enumerate(row_data, start=1):
                col_name = columns[col_idx - 1] if col_idx - 1 < len(columns) else ""
                cell = ws.cell(row=current_row, column=col_idx)
                cell.font = row_font
                cell.fill = row_fill
                cell.border = thin_border

                # Format & Align Values
                if isinstance(value, (int, float)):
                    cell.value = value
                    cell.alignment = Alignment(horizontal="right", vertical="center")
                    if col_name in currency_cols:
                        cell.number_format = '₹#,##0.00'
                    elif col_name in percentage_cols:
                        cell.number_format = '0.0%'
                    else:
                        cell.number_format = '#,##0.00' if isinstance(value, float) else '#,##0'
                else:
                    cell.value = str(value) if value is not None else ""
                    # Center dates or short codes, left-align text
                    val_str = str(cell.value)
                    if len(val_str) <= 12 and any(c in val_str for c in ["-", "/", "2024", "2025", "2026"]):
                        cell.alignment = Alignment(horizontal="center", vertical="center")
                    else:
                        cell.alignment = Alignment(horizontal="left", vertical="center")

            current_row += 1

        # Totals Row (optional)
        include_totals = sheet_spec.get("include_totals_row", False) and len(rows) > 0
        if include_totals:
            ws.row_dimensions[current_row].height = 26
            ws.cell(row=current_row, column=1, value="Total").font = total_font
            ws.cell(row=current_row, column=1).border = total_border
            ws.cell(row=current_row, column=1).fill = total_fill
            ws.cell(row=current_row, column=1).alignment = Alignment(horizontal="left", vertical="center")

            for col_idx in range(2, len(columns) + 1):
                col_name = columns[col_idx - 1]
                sample_vals = [r[col_idx - 1] for r in rows if col_idx - 1 < len(r)]
                numeric_vals = [v for v in sample_vals if isinstance(v, (int, float))]
                
                cell = ws.cell(row=current_row, column=col_idx)
                cell.font = total_font
                cell.border = total_border
                cell.fill = total_fill
                cell.alignment = Alignment(horizontal="right", vertical="center")

                if numeric_vals and col_name not in percentage_cols:
                    col_letter = get_column_letter(col_idx)
                    cell.value = f"=SUM({col_letter}{start_row + 1}:{col_letter}{current_row - 1})"
                    if col_name in currency_cols:
                        cell.number_format = '₹#,##0.00'
                    else:
                        cell.number_format = '#,##0.00'
                else:
                    cell.value = ""

            current_row += 1

        # Freeze panes below header
        if sheet_spec.get("freeze_header", True):
            ws.freeze_panes = f"A{start_row + 1}"

        # Enable AutoFilter (excluding totals row)
        if columns and rows:
            end_col_letter = get_column_letter(len(columns))
            data_end_row = current_row - 2 if include_totals else current_row - 1
            if data_end_row >= start_row + 1:
                ws.auto_filter.ref = f"A{start_row}:{end_col_letter}{data_end_row}"

        # Auto-adjust column widths (with generous padding for currency symbols)
        if sheet_spec.get("auto_width", True):
            for col in ws.columns:
                max_len = 0
                col_letter = get_column_letter(col[0].column)
                for cell in col:
                    val_str = str(cell.value or "")
                    if cell.row == 1:
                        continue  # ignore banner title row in width calculation
                    # Extra len padding if number formatted
                    if isinstance(cell.value, (int, float)):
                        val_str = f"₹{val_str}.00"
                    max_len = max(max_len, len(val_str))
                ws.column_dimensions[col_letter].width = max(max_len + 6, 16)

    # Charts Processing
    charts_spec = spec.get("charts", [])
    for chart_spec in charts_spec:
        target_sheet_name = chart_spec.get("sheet_name")
        if target_sheet_name not in wb.sheetnames:
            target_sheet_name = wb.sheetnames[0]
        
        c_ws = wb[target_sheet_name]
        chart_type = chart_spec.get("chart_type", "bar")

        if chart_type == "line":
            chart = LineChart()
        elif chart_type == "pie":
            chart = PieChart()
        else:
            chart = BarChart()

        chart.title = chart_spec.get("title", "Chart")
        chart.style = 10
        chart.width = 16
        chart.height = 10

        # Find column indices for categories and values
        cols_in_sheet = []
        for cell in c_ws[3]:
            if cell.value:
                cols_in_sheet.append(str(cell.value))
        
        cats_col_name = chart_spec.get("categories_column")
        vals_col_name = chart_spec.get("values_column")

        cats_idx = cols_in_sheet.index(cats_col_name) + 1 if cats_col_name in cols_in_sheet else 1
        vals_idx = cols_in_sheet.index(vals_col_name) + 1 if vals_col_name in cols_in_sheet else (2 if len(cols_in_sheet) > 1 else 1)

        # Exclude Total row from chart data
        max_r = c_ws.max_row
        has_total = any(str(c_ws.cell(row=max_r, column=c).value).lower() == "total" for c in range(1, 3))
        chart_end_row = max_r - 1 if has_total else max_r

        if chart_end_row >= 4:
            data_ref = Reference(c_ws, min_col=vals_idx, min_row=3, max_row=chart_end_row)
            cats_ref = Reference(c_ws, min_col=cats_idx, min_row=4, max_row=chart_end_row)

            chart.add_data(data_ref, titles_from_data=True)
            chart.set_categories(cats_ref)

            # Place chart cleanly to the right of the table
            chart_col_letter = get_column_letter(len(cols_in_sheet) + 2)
            c_ws.add_chart(chart, f"{chart_col_letter}3")

    wb.save(file_path)
    LOGGER.info("excel_generator.created", path=file_path, filename=filename)
    return file_path, filename
